name: Upload & Download Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  path_to_artifact: destination

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # debug:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Debug
  #       run: |
  #         echo "${{ toJson(github.event) }}"

  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3/node20
        with:
          name: my-artifact
          path: |
            .act/issue.opened.json
            act.issue_opened
            act.push
            act.workflow_dispatch
            .github/

  download:
    runs-on: ubuntu-latest

    needs: upload

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3/node20
        with:
          name: my-artifact
          path: ${{ env.path_to_artifact }}

      - run: ls -laR ${{ env.path_to_artifact }}
