name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
      deploy:
        description: 'Deploy to environment'
        required: true
        default: 'false'

jobs:
  # debug:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Debug
  #       run: |
  #         echo "${{ toJson(github.event) }}"

  environment_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    outputs:
      environment: ${{ steps.env.outputs.environment }}
      deploy: ${{ steps.deploy.outputs.deploy }}

    steps:
      - name: Environment
        id: env
        run: |
          echo "environment=my-environment-${{ github.event.inputs.environment }}" >> "$GITHUB_OUTPUT"

      - name: Deploy
        id: deploy
        run: |
          echo "deploy=my-deploy-${{ github.event.inputs.deploy }}" >> "$GITHUB_OUTPUT"

  print_environment_deploy:
    runs-on: ubuntu-latest

    needs:
      - environment_deploy

    steps:
      - name: Environment and Deploy
        run: |
          echo "::notice title=environment::${{ needs.environment_deploy.outputs.environment }}"
          echo "::notice title=deploy::${{ needs.environment_deploy.outputs.deploy }}"
